### ISSUE TITLE
Any chance to show us how we can install this on our server

### ISSUE THREAD

**Issue by Soubisan** [kamiljalowiczor/EZ-Tournament#1]
Heyo this bracket is really cool!
Is there any chance that you can show us how to install it ? 

I already tried with npm 'npm run build:frontend && npm run start' but theres so many errors and warnings, i cant see trough. :) 

greetings

**Comment by kamiljalowiczor** [comment]
hey, thanks! i didn't expect anyone to ever post anything under this project, so that's a nice surprise.

to run the whole thing you will need two terminals, one for the server, and one for the front-end:

first run `npm i`
then, to launch the server simply run  `npm start`
and for front-end use `npm run start:frontend:dev`

there might be a bit of trouble building and developing the server side, because it requires having .env file that for obvious reasons is not included in this repository. you could try to launch it anyway, by commenting out these lines in app.js.
![image](https://user-images.githubusercontent.com/57040395/195686788-920b4fe8-d888-4f60-810c-a0237efce950.png)
the server won't be any useful, because every single API request will fail, but at least it should launch.

alternatively, you could try creating your own firebase db, which is very easy and doesn't take much time. if you decide to do so, then create .env file in your project and fill the template:

<pre>
DATABASE_URL=XXXX
JWT_CLIENT_EMAIL=XXXX
JWT_PRIVATE_KEY=XXXX 
</pre>

 (i think the JWT things are only needed for deployment and you don't need them for local development, but i'm not 100% sure)

**Comment by Soubisan** [comment]
Hello ! Thank you very much for your answer! 
It works with your help for local development. :)
